site: blog.kukuh.syafaat.id
title: blog.kukuh.syafaat.id
greetings: blog.kukuh.syafaat.id
description: >-
  blog blog blog
lang: id-ID
timezone:  Asia/Jakarta
#repo: https://github.com/cho2/cho2.github.io # site repo [optional]
data-theme: light # default theme "dark" | "light"

author:
  name: Kukuh Syafaat (ꦏꦸꦏꦸꦃ شَفَٰعَةٌ)
  bio: FOSS Enthusiast & Part Time Musician
  userpicture: https://pbs.twimg.com/profile_images/817666937068994561/WH1WefHR_400x400.jpg
  username: cho2 # general username
  github: cho2 # github username
  twitter: cho2MLHC # twitter username
  email: kukuh@syafaat.id # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://blog.kukuh.syafaat.id" # Domain Name of host. [username].github.io for github pages
baseurl: "/" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:title/
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


